### ISSUE TITLE
Get up to date version whenever package is imported

### ISSUE THREAD

**Issue by ceball** [ioam/autover#13]
I'd like a package to show "the correct version" when it's imported from: (1) setup.py install, (2) git dir, (3) setup.py develop, (4) conda install - whenever those things are created (i.e. not just releases).

I've started a PR to test these things: #11 

(Some more discussion of this topic was in #2.)

**Comment by jlstevens** [comment]
As far as I know, all four cases you now mentioned work. If you have any counter examples, I am happy to look at them and implement any required fixes.

**Comment by jlstevens** [comment]
I believe all these cases are now handled since #15 was merged. Closing.
