### ISSUE TITLE
Get version from directory name for git archive against a tag

### ISSUE THREAD

**Issue by jlstevens** [ioam/autover#27]
If you do pip+git archive against master, you'll get ``0+unknown`` using versioneer. However if you do it against a tag, it figures out the version.

The way it does this is by extracting the tag from the directory name created by ``git archive``. Autover could use the same hack, creating a ``.version`` file when it has a chance using the information parsed from the directory name.

Here is how [versioneer does it](https://github.com/pyviz/nbsite/blob/master/versioneer.py#L529):

```python
def versions_from_parentdir(parentdir_prefix, root, verbose):
    """Try to determine the version from the parent directory name.
    Source tarballs conventionally unpack into a directory that includes both
    the project name and a version string. We will also support searching up
    two directory levels for an appropriately named parent directory
    """
    rootdirs = []
    for i in range(3):
        dirname = os.path.basename(root)
        if dirname.startswith(parentdir_prefix):
            return {"version": dirname[len(parentdir_prefix):],
                    "full-revisionid": None,
                    "dirty": False, "error": None, "date": None}
        else:
            rootdirs.append(root)
            root = os.path.dirname(root)  # up a level
    if verbose:
        print("Tried directories %%s but none started with prefix %%s" %%
              (str(rootdirs), parentdir_prefix))
    raise NotThisMethod("rootdir doesn't start with parentdir_prefix")
```

This is pretty hackish but it does eke out the last bit of version information that git archive doesn't officially make available. I'm not sure what priority this should have but personally I think pip+git clone is a perfectly reasonable recommendation for users who want to keep up with development.

**Comment by jlstevens** [comment]
It is probably worth mentioning what autover currently does for all uses of git archive: it will give you something like ``0.0.0+g8374cef6f.gitarchive``. This isn't useless as the SHA is an *exact* specification of the version but it is annoying that you lose the release (which is what the hack described above would address).

**Comment by jbednar** [comment]
And losing the release is bad, because the release numbers form an ordering that pip uses to determine which version is newer; pip can't use SHAs the same way.

**Comment by jlstevens** [comment]
The above PR has been merged and it works although you still need to use a git source in meta.yaml for conda forge as the directory name isn't preserved when conda build runs. Closing.
